name: WplaceTimeLapse

on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  WplaceTimeLapse:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: PIP
        run: |
          pip install aiohttp pillow

      - name: Python
        run: |
          python ".github/workflows/script.py"

      - name: Git
        run: |
          git config user.email "actions@users.noreply.github.com"
          git config user.name "github-actions"
          git add *
          if ! git diff --cached --quiet; then
            git commit -m "Actions"
            git push
          fi
